### PR TITLE
sverilog flag

### PR DESCRIPTION
**Pull request by alaindargelas**
Signed-off-by: Alain Dargelas <alain.dargelas@gmail.com>

### CODE REVIEW

**Review by tgorochowik — COMMENTED** [review]
LGTM, Is there a reason the comments are not aligned to code though?

**Comment by alaindargelas** [comment]
My coding style. The formater does not seem to mind either.
    On Tuesday, May 25, 2021, 10:16:07 PM GMT-10, Tomasz Gorochowik ***@***.***> wrote:  
 
 


@tgorochowik commented on this pull request.

LGTM, Is there a reason the comments are not aligned to code though?

**Comment by alaindargelas** [comment]
Something unreasonable is happening here, the Code Quality check complains about code that the "make format" formatted!
Please help @tgorochowik .

**Comment by tgorochowik** [comment]
Maybe there is a new yapf release which produces a different output than expected?
For this reason the version required in sv-tests is frozen (see: https://github.com/SymbiFlow/sv-tests/blob/master/conf/requirements.txt#L5)

Could you check if your yapf version is the same? If not try reinstalling it with:
```
pip3 install --upgrade --force-reinstall -Iv yapf==0.30.0
```

**Review by tgorochowik — APPROVED** [review]
LGTM, thanks for the changes

**Pull request merged**
