### PR TITLE
 missing ; after while loop

### PR DESCRIPTION
**Pull request by alainmarcel**
missing ; after while loop

Signed-off-by: Alain Dargelas <alainmarcel@yahoo.com>

### CODE REVIEW

**Comment by mithro** [comment]
Hi @alainmarcel,

To get rid of the redundant merge commits you want to do a `git fetch upstream` then a `git rebase upstream/master`.

You might want to do an "interactive rebase" with `git rebase -i upstream/master` which will let you describe which commits you want to be included in the rebase.

Thanks!

**Comment by alainmarcel** [comment]
Hi Tim, 
I started all fresh from a new fork, I deleted my old fork that was polluted by a massive push of all the rest ma modified, I created a new directory, git pull, and only modified 1 file, are you saying there are still unwanted files in this very pull request,
How is that possible?

Thanks,
Alain

**Comment by mithro** [comment]
Yes, see the commits tab - https://github.com/SymbiFlow/sv-tests/pull/116/commits

**Comment by alainmarcel** [comment]
@mithro, I think it is fixed.

**Comment by mithro** [comment]
@alainmarcel Looks like it! Will wait for someone who knows SystemVerilog better to confirm it should be merged.

(@hzeller)

**Pull request merged**
