### PR TITLE
Update ivtest with code cleanup

### PR DESCRIPTION
**Pull request by caryr**
Signed-off-by: Cary R <cygcary@yahoo.com>

### CODE REVIEW

**Comment by tgorochowik** [comment]
@caryr would you mind providing a short summary of the changes in your PRs regarding the ivtests updates?

Your work is very much appreciated and having that sort of summary would allow us to verify those changes much quicker

**Comment by caryr** [comment]
I updated ivtest and added/removed some items in the exclusion list for ivtest to make it more compatible given the requests in #1271. This is 100% focused on ivtest and what part of it is used.

**Comment by caryr** [comment]
Are you requesting a list of changes to the actual ivtest repo? Because checking in the two commits should have made it obvious the simple changes made inside sv-tests. You can assume I will not remove anything from the exclusion list until I expect it to be handled correctly in ivtest.

**Comment by caryr** [comment]
I just pushed some more changes: This reworks the following:

Moves some tests that are not implemented in Icarus yet from the CE (compile error) to normal so they will pass in sv-tests for tools that do support the functionality.

For now exclude the tests that check for always processes having delays. Eventually this should be marked as passing for other tools that do not check this and fail for Icarus

We have a similar check for unexpected delays added to always_* process and these have also been excluded.

Eventually I would like to make the above two know which environment was being used and switch from CE to normal depending on which tool is processing them. This will require some larger changes to sv-tests since the ivtest list needs to be generated more dynamically.

**Comment by caryr** [comment]
I also adds the ability to skip test marked NI (Not Implemented)

**Review by tgorochowik — APPROVED** [review]
Sounds good, thanks

**Pull request merged**
