### PR TITLE
kokoro: add periodic.cfg

### PR DESCRIPTION
**Pull request by joannabrozek**
Ref: https://github.com/SymbiFlow/sv-tests/pull/1329#issuecomment-778697671

### CODE REVIEW

**Review by mithro — APPROVED** [review]
LGTM!

**Comment by tgorochowik** [comment]
@mithro Should we also make the periodic builds deploy the report? I am not sure if its a good idea to have two jobs deploying the report, but maybe we should switch it to the periodic builds?
https://github.com/SymbiFlow/sv-tests/blob/5028553ce2539f848c16b411f9f49f447d800fee/.github/kokoro/run.sh#L105

**Comment by mithro** [comment]
@tgorochowik Waiting on @hzeller to approve the internal change before it will start running.

**Comment by mithro** [comment]
> @mithro Should we also make the periodic builds deploy the report? I am not sure if its a good idea to have two jobs deploying the report, but maybe we should switch it to the periodic builds?
> https://github.com/SymbiFlow/sv-tests/blob/5028553ce2539f848c16b411f9f49f447d800fee/.github/kokoro/run.sh#L105

Maybe we can deploy to different branches?

**Comment by mithro** [comment]
Seems to be running now....
Screenshot from 2021-02-16 21-04-06

**Comment by mithro** [comment]
Screenshot from 2021-02-16 21-05-48

**Comment by mithro** [comment]
Example run - https://source.cloud.google.com/results/invocations/3b278dd7-c6bf-47be-8b3f-e0e097f0d986/details

**Comment by tgorochowik** [comment]
Great, thanks!

**Pull request merged**
