### PR TITLE
Test report analyzer: temporary PR

### PR DESCRIPTION
**Pull request by lpawelcz**
This PR is for testing changes introduced by https://github.com/SymbiFlow/sv-tests/pull/1317
CI run in this PR should execute workflow `sv-test-ci` and after that, second workflow `comment-pr` should be triggered. 
We expect that this workflow will put a table with comparison of test results between current results from https://symbiflow.github.io/sv-tests-results/ and this PR.

PR will be closed after confirming that commenting feature is working properly.

### CODE REVIEW

**Comment by tgorochowik** [comment]
It works 🎉

CC @hzeller

**Comment by hzeller** [comment]
:raised_hands: Yay, this is really useful!

Now the question I guess is why there were any changes at all, as this was just a README change and why are some tests in some tools removed ?

Do some of these tests are close to timeout or have random crashes so that could explain these differences ? If so, we might need to dig down and find where the flaky invocations are. There is for instance the `AllowedTimeout` column; if we compare that with the `TimeWall` we can find timeouts.

**Comment by tgorochowik** [comment]
I think that most of these changes may be caused by new conda packages versions which are built independently from this repository. The changes in Verilator and Slang are probably mostly caused by this.

But the smaller numbers could probably mean that there are some flaky tests, timing out is indeed a plausible reason.

What is even weirder though is why some of the tools ran 15 fewer tests than earlier. Even the generated tests come from submodules so it shouldn't have changed.

**Comment by mithro** [comment]
@tgorochowik -- We should setup a github action / kokoro run which runs the tests on a regular schedule and checks the output changes?

**Comment by tgorochowik** [comment]
The report is currently uploaded by kokoro so I think it would be preferable to setup periodical (daily?) builds using it. Can this be done?

I know it is fairly easy to setup a cron job for gha but that would mean we would have to move to whole report generation to gha too

**Comment by mithro** [comment]
Yes, I can set up period builds on Kokoro.

**Comment by mithro** [comment]
@tgorochowik - If you add a `periodic.cfg` file in [`.github/kokoro`](https://github.com/SymbiFlow/sv-tests/tree/master/.github/kokoro) (see the [`continuous.cfg`](https://github.com/SymbiFlow/sv-tests/blob/master/.github/kokoro/continuous.cfg) as an example) then it should run every 6 hours.

**Pull request closed without merging**
