### PR TITLE
[dv:axi_vip] Addign initial version of AXI VIP

### PR DESCRIPTION
**Pull request by rasmus-madsen**
Initial version of AXI VIP I need to check location is ok and that files has been scrubbed ok before converting to actual PR

Signed-off-by: Rasmus Madsen <rasmus.madsen@wdc.com>

### CODE REVIEW

**Comment by rasmus-madsen** [comment]
hi @kgugala 
could you take a quick look at this and see if it looks as expected and if the location is ok?
I will do a second check of the files over the weekend to make sure the files are clean.

**Comment by hzeller** [comment]
also @tgorochowik is a good person to give feeback.

As location, I suggest something like `third_party/tests/axi_vip/`

**Comment by rasmus-madsen** [comment]
> also @tgorochowik is a good person to give feeback.
> 
> As location, I suggest something like `third_party/tests/axi_vip/`

@mgielda or @kgugala  do you have any comments on this if not I will update the location and update the PR

**Comment by kgugala** [comment]
the `third_party/tests/axi_vip/` seems fine. We still need to go through all the code in the PR, but moving it to `third_party` is sth we should do

**Comment by rasmus-madsen** [comment]
> the `third_party/tests/axi_vip/` seems fine. We still need to go through all the code in the PR, but moving it to `third_party` is sth we should do

np closing PR and opening a new one

**Pull request closed without merging**
