### PR TITLE
Add Surelog to tested tools.

### LINKED ISSUE #440: Add SureLog to sv-tests
https://github.com/alainmarcel/Surelog

### PR DESCRIPTION
**Pull request by hzeller**
Fixes #440

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
Currently using `-nobuiltin` until https://github.com/alainmarcel/Surelog/issues/66 exists.

**Comment by hzeller** [comment]
Could you have a look @alainmarcel if this looks good ?

**Comment by alainmarcel** [comment]
It fails...

**Comment by hzeller** [comment]
Don't worry about the failure for now: the Travis test is failing due to some other problem right now.

**Comment by mithro** [comment]
```
The command "make generate-tests" exited with 0.
0.11s$ make tests USE_ALL_RUNNERS=1 -j2
Makefile:68: Runners found: Slang Yosys tree_sitter_verilog sv_parser moore Icarus Verilator Odin Sv2v_zachjs
Makefile:69: Runners defined: Slang Yosys tree_sitter_verilog sv_parser moore Icarus Verilator Surelog Odin Sv2v_zachjs
Makefile:70: *** Some runners are missing.  Stop.
The command "make tests USE_ALL_RUNNERS=1 -j2" exited with 2.
0.11s$ make report USE_ALL_RUNNERS=1
Makefile:68: Runners found: Slang Yosys tree_sitter_verilog sv_parser moore Icarus Verilator Odin Sv2v_zachjs
Makefile:69: Runners defined: Slang Yosys tree_sitter_verilog sv_parser moore Icarus Verilator Surelog Odin Sv2v_zachjs
Makefile:70: *** Some runners are missing.  Stop.
The command "make report USE_ALL_RUNNERS=1" exited with 2.
```

**Comment by hzeller** [comment]
mmh, the script doesn't seem to run `make runners`. Is it expecting the binaries to come from somewhere else ?

**Comment by tgorochowik** [comment]
Yes, we do not build the runners in the CI but create a conda package for each one instead (See: https://github.com/SymbiFlow/sv-tests/blob/a3488850cd45840977074eea83c9656055e54fcf/conf/environment.yml )

The makefiles for the runners are still there to allow users to do a local build without conda easily.

So generally we should add a conda package for surelog, or as a temporary workaround call `make surelog` by hand.

**Comment by mithro** [comment]
Please rebase.

**Comment by hzeller** [comment]
Depends on https://github.com/SymbiFlow/conda-packages/pull/57 so that we can use `surelog` from the conda package.

**Comment by hzeller** [comment]
Rebased and also updated to latest build-instructions.
But given that binary availability is based on conda now, we have to wait until that binary shows up there.

I suggest squash-merge once we're there as a bunch of changes have been pushed leading to the final result.

**Comment by hzeller** [comment]
So looks like now we'd be exceeding the Travis build-time, while the Kokoro build succeeded.

How do we proceed: splitting travis build first ?

**Pull request merged**
