### PR TITLE
Remove chapter tags from UVM tests

### PR DESCRIPTION
**Pull request by tgorochowik**
Basically a recursive `s/tags: 18.* uvm/tags: uvm uvm-random/g` in `tests/chapter-18`.

Closes: #1146

### CODE REVIEW

**Review by wsnyder — APPROVED** [review]
Thanks for updating these.

**Comment by hzeller** [comment]
All of these have the `uvm-random` tag set; do all of these use random ?

**Comment by tgorochowik** [comment]
@hzeller chapter 18 is called "Constrained random value generation" so all of these tests are indeed either using random or are related to using it

**Comment by tgorochowik** [comment]
Changed the substitute command to `'s/tags: (18.*) uvm/tags: uvm-\1 uvm/g'` to reflect the discussion from #1146

**Comment by wsnyder** [comment]
Thanks, this fixes my issue too.

**Pull request merged**
