### PR TITLE
Add tests for triggering and waiting for named events

### PR DESCRIPTION
**Pull request by MegabytePhreak**
These are described in chapter 15.5 of the LRM.

The tests cover direct and hierachical references to events within
modules, as well as direct references within a class.

### CODE REVIEW

**Comment by caryr** [comment]
Should the normal and non-blocking event checks be in separate tests?

**Comment by MegabytePhreak** [comment]
I'm open to the idea. I'm not sure what the project preference is. They both come under the same section in the LRM. 
I've honestly never used the non-blocking form myself. 

I actually found an interesting hole in the spec while writing this test. Namely you can put an event in a class, but can't refer to it using this.some_event for either triggering or waiting. Multiple commercial tools will accept this, but reading the LRM it doesn't seem to be permitted, since this is a reserved keyword and not an identifier.

**Review by tgorochowik — COMMENTED** [review]
Thank you for your contribution!

Looks good to me in general, I agree with @caryr that it would be nice to create two separate tests for blocking and non-blocking triggers - would you mind splitting that to two tests?

**Review by tgorochowik — APPROVED** [review]
Since these are not a proper simulation tests but rather tests that verify whether the operators can be parsed in various contexts I think the changes are enough.

LGTM, thanks for the contribution!

**Pull request merged**
